### ISSUE TITLE
Publish Vedic heritage dictionary

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/stardict-sanskrit#12]
Link - http://ignca.nic.in/vedic_heritage/Vedic_heritage_Illustratred_dic_hindi.pdf 

Motivation- very important for students and practitioners of kalpa.

Pdf uses a strange non-unicode encoding. But, I think it may be converted to unicode.

**Comment by damooo** [comment]
bhai, is it decoded? ,Now i got  a sanskrit-telugu-english dictionary published in which devanagari is in same encoding.

**Comment by vvasuki** [comment]
Yes - it was already published, dAmodara - https://github.com/sanskrit-coders/stardict-sanskrit/tree/master/sa-head/vedic-rituals-hi  (see announcement - https://groups.google.com/forum/#!searchin/sanskrit-programmers/kalpa%7Csort:relevance/sanskrit-programmers/64rnJ0WnlxY/zZnzBa-QCAAJ ). 
A person called venkaTesha [had done](https://groups.google.com/forum/#!searchin/sanskrit-programmers/kalpa%7Csort:relevance/sanskrit-programmers/4eiGWG_rs54/2jQFSkQ1AwAJ) the decoding with his software.
