### ISSUE TITLE
Export padamanjarI to babylon format

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/stardict-sanskrit#16]
Example: https://github.com/sanskrit-coders/stardict-sanskrit/blob/master/sa-vyAkaraNa/laghu-kaumudi/laghu-kaumudi.babylon

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/padamanjari/blob/master/make_babylon.py is the script responsible to convert https://github.com/drdhaval2785/padamanjari/blob/master/padamanjari.txt (raw text format scraped from HTML) to a babylon format.


https://github.com/drdhaval2785/padamanjari/blob/master/babylon/padamanjarI.txt is the first babylon version of this grammar treatise.

@vvasuki 
Please let me know the bugs / enhancements as usual.

Known issue - The text of this book is full of errors. So the resultant dict will be full of errors. Cleaning may take years. 

Let us use whatever we have. As and when corrections happen in https://github.com/drdhaval2785/padamanjari/ repository, I will post an announcement here. New file can be grabbed from the same location and stardict regenerated.

**Comment by gasyoun** [comment]
> The text of this book is full of errors

Maybe @vvasuki is interested in developing the spell checker based on what's you've got?

**Comment by vvasuki** [comment]
What a surprise! Thanks, dhaval! Please rename it to .babylon.

Great idea, Marcis - i'll give it a shot after I regain greater control over my time (expected in a few months).

**Comment by vvasuki** [comment]
@drdhaval2785 - Numbers are in English - can you move them to devanAgarI as well, please? English numbers and headwords will be automatically readded later.

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/padamanjari/blob/master/babylon/padamanjarI.babylon has incorporated your suggestions @vvasuki.

**Comment by vvasuki** [comment]
@drdhaval2785 - my scripts report these errors:

```
19:36:50 dictTools 64 --- java.util.NoSuchElementException: next on empty iterator
19:36:50 dictTools 65 --- line: (४.४.४९|| ४.४.४९|४.४.४९ ,3513)
19:36:51 dictTools 64 --- java.util.NoSuchElementException: next on empty iterator
19:36:51 dictTools 65 --- line: (५.१.१२१|| ५.१.१२१|५.१.१२१ ,5259)
19:36:52 dictTools 64 --- java.util.NoSuchElementException: next on empty iterator
19:36:52 dictTools 65 --- line: (६.३.८५|| ६.३.८५|६.३.८५ ,7590)

```
Also, there is some initial line which needed to be removed .. Can you take a look?

**Comment by drdhaval2785** [comment]
Looked. There were irregular line breaks in these lines.
`XYZ ॥ ४.४.४९ ॥`
was wrongly written as
```
XYZ
॥ ४.४.४९ ॥
```

**Comment by drdhaval2785** [comment]
@vvasuki 

Your suggestions have been incorporated and the babylon file updated.
Please see so that it can be added to stardict.

**Comment by vvasuki** [comment]
Needed to add a newline in the end ("** (process:7606): CRITICAL **: Error, expected an empty line after definition: 10350."). But done.
