### ISSUE TITLE
Ready The Vedic Index of Names and Subjects for wiktionary upload

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/stardict-sanskrit#17]
namaste dAmodara,

You had earlier created the following files:

-  stardict-sanskrit/sa-kAvya/vedic_index/vedic_index.wiki_ref 
-  stardict-sanskrit/sa-kAvya/vedic_index/vedic_index.wiki_nref 

to facilitate uploading the Vedic Index of Names and Subjects to wiktionary. That's great! Some minor fixes are required before my bot script can dump it into the wiktionary website:

- Make everything one file - don't keep the references seprately. I should be able to just take the wikitext from this file and directly write to wiktionary.
- Only retain the main devanAgarI headword (अक्ष, not  "१। अक्ष").

**Comment by damooo** [comment]
added. vedic_index.wiki file.

**Comment by vvasuki** [comment]
Thanks! Added everything to [wiki](https://sa.wiktionary.org/wiki/%E0%A4%B5%E0%A4%B0%E0%A5%8D%E0%A4%97%E0%A4%83:%E0%A4%AF%E0%A4%A8%E0%A5%8D%E0%A4%A4%E0%A5%8D%E0%A4%B0%E0%A5%8B%E0%A4%AA%E0%A4%BE%E0%A4%B0%E0%A5%8B%E0%A4%AA%E0%A4%BF%E0%A4%A4%E0%A4%95%E0%A5%8B%E0%A4%B6%E0%A4%BE%E0%A4%82%E0%A4%B6%E0%A4%83-Vedic_Index_of_Names_and_Subjects)
