### ISSUE TITLE
Some help for linux users

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#26]
I recently tried to clone this repository.
4% = 144 MB.

Majority of it was the git version history.
The data has not started downloading yet.

It would be useful if we have some shell script which downloads only the current files of this repo (no need to have 1 GB+ git history for most of the users - other than developers).

I tried tars folder.
But it has only 4 / 6 files seen in this repo (required by programs).
When I exported them, stardict didnt show the dictionary (tattvabodhini).

**Comment by damooo** [comment]
we may can  use --depth attribute. like fallow.

git clone --depth 1 https://github.com/sanskrit-coders/stardict-sanskrit.git

it will clone only present files, and allow pushing too.

**Comment by drdhaval2785** [comment]
Lovely. So there is a git facility for it.
I have been working with git for past 3-4 years and was not aware of this.

@vvasuki, Can this be incorporated in the readme itself? So that people interested in only repos can get required items without hassle.

**Comment by vvasuki** [comment]
Done! Thanks @damooo - I did not know also.
