### ISSUE TITLE
remove old tars

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#30]
When I tried to run `make DICTS="siddhAnta-kaumudI'`
The following happened.

1. There was old tar fetched from git pull.
2. The script made new tar having new time stamp.
3. Script also updated tars.MD to have two siddhAnta-kaumudI (old + new).

It makes sense to remove the old tar from directory before regenerating tars.MD.

It is not usually needed to keep old file. Git takes care of it. We can always see the history and get the old file.

**Comment by gasyoun** [comment]
> We can always see the history and get the old file.

Agree.

**Comment by vvasuki** [comment]
Seems to be a transient error. unable to reproduce. have fixed the excess siddhAnta-kaumudI tar now.
