### ISSUE TITLE
AP90 added

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#32]
Apte's 1890 version added into sa-head folder.
Works well on my colordict for android.

**Comment by vvasuki** [comment]
Super! I suppose that it is different from apte-sa? Can you please rename it to apte-1890, so that users can understand what is being offered better?

**Comment by drdhaval2785** [comment]
I am not sure whether this is different from apte-sa or not.
There are two distinct dictionaries composed by Apte.
1. http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/web/webtc2/index.php is the one published in 1890.
and
2. one published in 1957 	Practical Sanskrit-English Dictionary, revised edition

What does apte-sa refer to is not clear to me.
In fact there are three apte versions now

apte-bi, apte-sa and apte-1890.

What are sources of apte-bi and apte-sa is not known to me. Maybe something taken from Cologne server long time ago. 2008 or so.

Whereas apte-1890 is taken from Cologne server (and can be updated frequently) with a lot of corrections incorporated into it. 

Renamed it to apte-1890 as suggested.

**Comment by vvasuki** [comment]
![image](https://cloud.githubusercontent.com/assets/2664797/24597772/998df82e-17fc-11e7-9111-4d7a74600b3c.png)
Dictionary still shows up as ap-90  - perhaps you need to regenerate the stardict files..

**Comment by gasyoun** [comment]
> What are sources of apte-bi and apte-sa is not known to me. Maybe something taken from Cologne server long time ago. 

http://dsal.uchicago.edu/dictionaries/

**Comment by vvasuki** [comment]
dsal is pretty tight fisted - usually won't give us copies. I think that @aupasana used old Cologne files.
