### ISSUE TITLE
Bopp Glossarium Sanscritum added

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#37]
A Sanskrit-Latin dictionary.
Short name BOP.
In stardict-sanskrit/sa-head/bopp folder.

**Comment by vvasuki** [comment]
suggest staying away from acronyms - lets make it glossarium_sanscritum plz..

**Comment by drdhaval2785** [comment]
Bopp is the author.

It is as intuitive as Apte.

**Comment by vvasuki** [comment]
> It is as intuitive as Apte.

This is like comparing [nandi hill](https://en.wikipedia.org/wiki/Nandi_Hills,_India) to Mount meru :-D . Most of us have no clue who this bopp is or what he created - so an intelligent choice cannot be made as to whether it should be installed. Hence the case for renaming to  glossarium_sanscritum

**Comment by drdhaval2785** [comment]
Ok. If you insist, I will change it to long one...

**Comment by gasyoun** [comment]
> Most of us have no clue who this bopp 

Most of us know Bopp, and only some Apte :+1: 
So let's leave it as BOP. glossarium_sanscritum means nothing, if you do not know Latin.

**Comment by vvasuki** [comment]
I know the choice @drdhaval2785 will make, but continuing the discussion just for fun:

> Most of us know Bopp, and only some Apte :+1:

"you" are far fewer in number (a few orders of magnitude fewer) than "us".

> So let's leave it as BOP. glossarium_sanscritum means nothing, if you do not know Latin.

Not so - you immediately know that it sounds like latin and that it has something to do with sanskrit.

**Comment by vvasuki** [comment]
For consumer convenience, I've now grouped sa-head dictionaries based on the dominant language of the entries.

> https://raw.githubusercontent.com/sanskrit-coders/stardict-sanskrit/master/sa-head/sa-entries/tars/tars.MD
> https://raw.githubusercontent.com/sanskrit-coders/stardict-sanskrit/master/sa-head/en-entries/tars/tars.MD
> https://raw.githubusercontent.com/sanskrit-coders/stardict-sanskrit/master/sa-head/other-indic-entries/tars/tars.MD
> https://raw.githubusercontent.com/sanskrit-coders/stardict-sanskrit/master/sa-head/other-entries/tars/tars.MD
