### ISSUE TITLE
Create plant-names dictionary

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/stardict-sanskrit#4]
We must produce a script to transform [snp.txt](https://github.com/sanskrit-coders/stardict-sanskrit/blob/master/sa-head/plant-names/mUlam/snp.txt) into a babylon dictionary.

Regarding scripting - scripts in https://github.com/sanskrit-coders/stardict-sanskrit/tree/master/sa-head/kalpadruma-sa/mUlam may help you with a speedy start!

**Comment by drdhaval2785** [comment]
The work done.
Now resides as Meulenbeld-Sanskrit-Names-of-Plants in our repository.

**Comment by gasyoun** [comment]
Well done.
