### ISSUE TITLE
Borooah added

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#40]
English - Sanskrit dictionary.

en-head/borooah folder.
Shortcode BOR

**Comment by vvasuki** [comment]
This is a wonderful contribution.

Here is a typical entry:

> monarchy
> MONARCHY: <BR>²I M.cal government: <BR>³1  राजशासनम्; <BR>³2 राजतन्त्रम्। <BR>²II Kingdom: q. v.:  राज्यम्। <BR> 
 
* Can we please add the sanskrit headwords (dudicing the prAtipadika-s where simple) as well? Otherwise, we cannot look it up using raajashaasana.
* What do the superscripts mean?? Should they point to footnotes or removed altogether?

**Comment by vvasuki** [comment]
File ends with a bad character , breaks some scripts -  java.nio.charset.MalformedInputException: Input length = 1 .

**Comment by drdhaval2785** [comment]
- Can we please add the sanskrit headwords (dudicing the prAtipadika-s
   where simple) as well? Otherwise, we cannot look it up using raajashaasana.


Possible, but far off. After some time.


   - What do the superscripts mean?? Should they point to footnotes or
   removed altogether?


Indentation level.

**Comment by drdhaval2785** [comment]
Now both conditions are taken care of.
