### ISSUE TITLE
Grassman added

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#43]
GRA

**Comment by vvasuki** [comment]
A typical entry:

> śvetá, a., weiss, licht, hell, glänzend [v. śvit]; insbesondere 2) Beiwort des weissen Rosses, welches die Aśvinen dem Pedu schenkten; auch 3) bildlich vom Gebete; 4) m., Leuchte(?).
> -ás vājī (agnís) 355,4; drapsás ná 603,6; (vā|yús) 607,3; yāmas a|sya (agnés) 846,9.
>  -4) … ná vikṣú 66,6 (agnís).
> -ám [m.]
> áśvam 593,3; agním 235,4; (vāyúm) 606,3; kaláśam 323, 5; 786,8.
>  -2) áśvam 116,6; 118,9; 119,10; 865,10.
> -ám [n.]
> rūpám 786,7.
> -ô [du.]
> (indrāgnī) 660, 8.
> -ā [dass.]
> vicakṣaṇā 661,9.
> -āsas ukṣáṇas 1024,2.
> -ān ádhinirṇijas 661,10 (Gegensatz kṙṣṇān).
> -áyā 3) dhiyā 646,19.
> 

improvements:
* Good to separate entries.
* Transliterate and hyperlink, present references better.
