### ISSUE TITLE
Goldstucker added

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#44]
GST

**Comment by vvasuki** [comment]
Good to separate entries:

> Tatpur. I. m. f. n. (-जः-जा-जम्)
>  ^1 Produced on a mountain, mountaineous.
>  ^2 Produced from a tree, vegetable.
> II. n. (-जम्) Bitumen. See शिलाजतु. E. अग and ज.
> 


Also, the dictionary seems incomplete - stops at अभ्याहित. Plz check.
