### ISSUE TITLE
Monier Williams 1872 added

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#47]
MW72

**Comment by vvasuki** [comment]
A typical entry:

> Druma, as, m. (said by some to be for druhma fr. rt. dṛh), a tree in general; a tree of Svarga or paradise; N. of a prince of the Kim-purushas; a prince of the Yakshas; (ā), f., N. of a river.
> --Druma-kinnara-prabha, as, m., N. of a prince of the Gandharvas.
> --Druma-kinnara-rāja, as, m., N. of Druma who was king of the Kin-naras.
> --Drumakinnararāja-paripṛććhā, f. ‘the questioning of Druma, king of the Kin-naras,’ N. of a Buddhist work.
> --Druma-nakha, as, m. ‘tree-nail,’ a thorn.
> --Druma-maya, as, ī, am, made of wood, wooden.
> --Druma-ratna-śākhā-prabha, as, m., N. of a prince of the Kin-naras.
> --Druma-vat, ān, atī, at, overgrown with trees, woody.
> --Drumavalka, as or am, m. or n. (?), the bark of a tree.
> --Druma-vyādhi, is, m. ‘tree-disease,’ lac, resin.
> --Druma-śīrsha, am, n. ‘tree-head,’ a sort of decoration on the upper part of a building or wall.
> --Druma-śreshṭha, as, m. ‘the best of trees,’ epithet of the palm tree (= tāla).
>  --Druma-shaṇḍa, am, n. an assemblage of trees; [cf. taru-shaṇḍa and taru-khaṇḍa.]
> --Druma-sena, as, m., N. of a king (identified with the Asura Gavishṭha).
> --Drumāmaya (ºma-āmº), as, m. ‘tree-disease,’ lac, the animal dye, resin; [cf. druma-vyādhi.]
> --Drumāri (ºma-ari), is, m. ‘the enemy of trees,’ an epithet of the elephant.
> --Drumālaya (ºma-ālº), as, m. a place of shelter or dwelling in trees.
> --Drumāśraya (ºmaāśº), as, ā, am, seeking shelter or dwelling in trees; (as), m. a lizard, chameleon.
> --Drumeśvara (ºmaīśº), as, m. ‘the king of trees,’ an epithet of the Pārijāta; the palm tree; an epithet of the Moon.
> --Drumotpala (ºma-utº), as, m. the tree Pterospermum Acerifolium (= karṇi-kāra).
> 


Again an excellent enhancement would be to separate meanings into different entries.
