### ISSUE TITLE
abhyankara-grammar file

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-coders/stardict-sanskrit#50]
https://github.com/sanskrit-coders/stardict-sanskrit/releases/download/2017-04-14/abhyankara-grammar__2017-02-23_20-48-43.tar.gz why it's so small? Can't open it in Notepad. Not Unicode?

**Comment by drdhaval2785** [comment]
Binary files compressed.
To be used with stardict readers.

**Comment by vvasuki** [comment]
You can open with some archive/ zip program (in ubuntu that would be archiver).
