### ISSUE TITLE
Many Many Many thanks

### ISSUE THREAD

**Issue by SrinivasRG** [sanskrit-coders/stardict-sanskrit#70]
I could not find a way to convey my gratitude.  So creating an issue!  Absolutely सुकृतोस्मि.  This dictionary is the most fantastic thing to happen in my life. 
- Srinivas

**Comment by drdhaval2785** [comment]
A little more info will help us. What dictionaries you use most?

**Comment by SrinivasRG** [comment]
I am most certainly willing to share any info. 

I am afraid you have mistaken me for a pandit, but I am only an enthusiast and a beginner (a serious one, at this moment). 

Short answer: Halayudha kosha, http://spokensanskrit.de and आख्यातचंद्रिका.  Any elaboration of आख्यातचंद्रिका beyond listing the alternatives is very welcome.

Long answer: 
I began to seriously learn (re-learn) संस्कृतम् about two months ago, mostly with google as my friend.
In the beginning I had to struggle hard even with keyboard input, but with ibus* packages on ubuntu(14.04) I am quite comfortable typing संस्कृतम्. First book of Sanskrit by RG Bhandarkar started me going. The Chitrapur Math website helped me a lot. http://spokensanskrit.de offers reliable help but not extensive enough. [sambhashanasandesha](http://www.sambhashanasandesha.in)   and  [ASSP](http://www.sanskrit.nic.in/ASSP/) by way of good example prose was helpful.  I also found  [this](http://tdil-dc.in/san/sandhi_splitter/index_dit.html) is very helpful.


Many of samskritam wiki pages are good but many of them are quite  poor examples of samskrita prose.

I was fortunate to find a nice scanned copy of  "halayudha kosha" pdf. Halayudha kosha is quite a nice thesaurus and I think it is not there in your collection.  You should probably add it, if you have not already.
अमरकोश by itself was well beyond my reach, till your dictionary put it inside of my reach. Nonetheless, even your dictionary version of अमरकोश does not give gender of a noun. The Most helpful, In your collection was आख्यातचंद्रिका.  There is a verb for every minute variation of mood and sense in संस्कृतम्, but, other than आख्यातचंद्रिका, I do not know any way of accessing this really rich repertoire.  For each suggestion of आख्यातचंद्रिका ( or the most used verbs )  if it is possible to add all the lakaara and karmani variations, the way this [website](http://www.verbix.com/webverbix/go.php?D1=211&T1=आस्)  does, probably that would be the best thing to happen.  

This is our second correspondence. 
The first one was when you answered my question on नमज्जनाभीष्टततिप्रदाभ्याम् , on another forum.

Okay so much for now, and I am quite sure I have bored you...

Thanks for your time. 
Srinivas

**Comment by vvasuki** [comment]
Is this pdf of halAyudha digitized (ie can you copy paste from it)? If so we might be able to include it here.

**Comment by SrinivasRG** [comment]
No it is not digitized.  I have shared the file. but it is in image format. Probably needs the OCR and then the effort of proof reading etc. [Attached](https://drive.google.com/open?id=0B56fHp6CfVVaVXktRmRKcHNCczA) anyhow.

And yes I am a fan of all संस्कृत सेवक s.  Thanks on behalf of all संस्कृतानुरागि s. 
- Srinivas
