### ISSUE TITLE
Remove IAST headwords from dicts

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/stardict-sanskrit#71]
Looking up rama in Goldendict desktop shows entries for ramā - not just in ap-1890 but every other dictionary. IAST conflicts with OPTITRANS, so should not be included as a headword. 

Snippet:

```
From ap-1890
ramaa

[रमयति रम्-अच्]
1 A wife, mistress.
2 N. of Lakshmî, the wife of Vishṇu, and Goddess of wealth.
3 Good luck, fortune.
4 Riches.
5 Splendour.
6 N. of the eleventh day in the dark half of Kârtika.
--Comp.
 --कांतः,
 --नाथः,
 --पतिः epithets of Vishṇu.
--प्रियः Vishṇu.
--यं a lotus.
--वेष्टः turpentine.
From apte-sa
ramaa

रमा [ramā], [रमयति रम्-अच्]
ramaa

A wife, mistress.
ramaa

N. of Lakṣmī, wife of Viṣṇu and Goddess of wealth; रमा यत्र न वाक् तत्र यत्र वाक् तत्र ना रमा Udb.
ramaa

Good luck, fortune.
ramaa

Riches.
ramaa

Splendour.
ramaa

N. of the eleventh day in the dark half of Kārtika. -Comp. -आस्पदः, -कान्तः, -नाथः, -पतिः epithets of Viṣṇu; Bhāg.1. 55.4. -प्रियः Viṣṇu. (-यम्) a lotus. -वेष्टः turpentine.
From aufrecht-catalogus-catalogorum
ramaa

रमा Candrālokaṭīkā by Vaidyanātha. Ben. 39. SB. 301.
From mw-sa
ramaa

रमा f. See. s.v.
ramaa

रमा f. of रमSee.
ramaa

रमा f. a wife , mistress W.
ramaa

रमा f. N. of लक्ष्मी, the goddess of fortune Bhartr2. BhP.
ramaa

रमा f. good luck , fortune , splendour , opulence Ca1n2.
ramaa

रमा f. splendour , pomp Bha1m.
ramaa

रमा f. N. of the 11th day in the dark half of the month कार्त्तिकCat.
ramaa

रमा f. of the syllable शॄम्(also रम) Sarvad.
ramaa


```

Yet to figure out which dictionary has these IAST keywords.

**Comment by vvasuki** [comment]
I earlier mistakenly thought that this was due to inclusion in ap-1890 - but it must be elsewhere. Looking.

**Comment by vvasuki** [comment]
Fixed purANa-encyclopedia and vedic_index.  

The pAli dicts still have IAST.

**Comment by vvasuki** [comment]
I deleted customized / stylized versions of vedic index dictionary which included IAST headwords and spoiling lookup experience.

**Comment by funderburkjim** [comment]
#### Optitrans question

Optitrans is new to me.

Is [this](https://sites.google.com/site/sanskritcode/optitrans) the defining document?

or more specifically [this table](https://docs.google.com/spreadsheets/d/1o2vysXaXfNkFxCO-WD77C4AEbXcAcJmDVgUb-E0mYbg/edit#gid=0) ?

What role does it play in the stardict dictionaries of stardict updater?

Is optitrans v1 used? or optitrans v2?

**Comment by vvasuki** [comment]
Fixed pAli dicts as well.

**Comment by vvasuki** [comment]
> What role does it play in the stardict dictionaries of stardict updater?

It lets Indic users do phonetically intuitive lookups (eg: raama, kRShNa, shankara).

> or more specifically [this table](https://docs.google.com/spreadsheets/d/1o2vysXaXfNkFxCO-WD77C4AEbXcAcJmDVgUb-E0mYbg/edit#gid=0) ?

yes

> Is optitrans v1 used? or optitrans v2?

v1. (v2 is used as a typing method with Ubuntu m17n package)

**Comment by vvasuki** [comment]
BTW, while fixing pALi, here is a simple scala function I wrote to convert only Indic IAST words to devanAgarI and optitrans while leaving english words alone.

![image](https://cloud.githubusercontent.com/assets/2664797/25508400/a40e89ee-2b66-11e7-8e60-b7ca37ff6fe5.png)

![image](https://cloud.githubusercontent.com/assets/2664797/25508413/b2c88548-2b66-11e7-9b17-9384f1f7abe3.png)

Actual code [here](https://github.com/sanskrit-coders/stardict-sanskrit/blob/master/bin/scripts/stardict_sanskrit/Dictionary.scala). Can be reused with slight modification for converting just the Indic words in dict entries as well.
