### ISSUE TITLE
Meta data lacking

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-coders/stardict-sanskrit#78]
@vvasuki I can't locate meta data about each file. Where does abhyankara-grammar__2017-06-05_14-22-30__0MB.tar.gz come from? Have never seen it before and started OCRing it a few years ago myself.

**Comment by vvasuki** [comment]
We've OCR-d and proofread it on wikisource (link in https://github.com/sanskrit-coders/stardict-sanskrit/issues/20 ). Please feel free to join the project (sent you an invite) and add a README.md in the appropriate folder linking to the wikisource page.

**Comment by drdhaval2785** [comment]
Now for Cologne dictionaries, LICENSE.xml holds metadata @gasyoun.

**Comment by gasyoun** [comment]
> LICENSE.xml holds metadata

Thanks.
