### ISSUE TITLE
Errors in script

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#79]
```
dhaval@dhaval-ThinkCentre-M73:~/stardict-sanskrit/sa-head/en-entries$ make DICTS="apte-1890"
bash ../../bin/babylon_add_optitrans.sh DICTS=apte-1890
/tmp/scalacmd7644707532748358040.scala:1: error: not found: value stardict_sanskrit
stardict_sanskrit.babylonProcessor.addOptitrans("DICTS=apte-1890".replace("DICTS=", ""))
^
one error found
makefile:15: recipe for target 'final_babylon' failed
make: *** [final_babylon] Error 1
```

**Comment by vvasuki** [comment]
I don't get this error. Observe that the instructions have changed and the scripts now refer to a new repository:
```
cat ../../bin/babylon_add_optitrans.sh
#!/bin/bash
# STARDICT_SANSKRIT_SCALA=`dirname $0`
PATH_TO_JARS=~/dict-tools
scala -classpath "$PATH_TO_JARS/bin/artifacts/*" -e "stardict_sanskrit.babylonProcessor.addOptitrans(\"$1\".replace(\"DICTS=\", \"\"))"
```

Please sync the `dict-tools` repo and retry

**Comment by drdhaval2785** [comment]
Now after dict-tools syncing this error is gone, but getting another kind of error.

Something related to make_tarballs.sh. I guess the URL was made a separate variable, but pwd|sed and a suoerfluous closing bracket still lingered on. Please check. First argument of make_tarballs is not uniform across subfolders.

**Comment by vvasuki** [comment]
Fixed the makefiles and make_tarballs.sh  - seems to be fine now. Please retry.

**Comment by drdhaval2785** [comment]
Ok. Will retry in evening and get back.

**Comment by drdhaval2785** [comment]
Works well.
