### ISSUE TITLE
Create spokensanskrit babylon and stardict dictionaries.

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/stardict-sanskrit#8]
shrI dAmodara has scraped spokensanskrit and has stored info in [this file](https://github.com/sanskrit-coders/stardict-sanskrit/blob/master/sanskrit-db/sanskrit.table). It would be very useful to make it available as babylon and stardict files. dAmodara - can you produce them?

**Comment by damooo** [comment]
working on it. but abruptly stopped, as i have no idea on proceding on one problem. As spokensanskrit is nicely in tabular form,  i tried  inthat format only, butt stardict compiler erasing white spaces,, and resulting an ugly result. i want to know any possiblity to overcome that?? like having <tr>, <td> tags , or what  ever?? ,.. and i am checking  babylon official bgl compiler for  that if possible. if there is any soln, please mention.  then after it is matter of  half aan hour : ), as i  already completed major part of work.

**Comment by vvasuki** [comment]
Can you give me an example such problematic overwrites? ie - what is the original entry, and what is the entry you get after stardict/ babylon compilation?

**Comment by damooo** [comment]
like i searched a random word, it will give all synonomical results in a tabular form like in this page
[http://spokensanskrit.de/index.php?beginning=0+&tinput=tree+&trans=Translate&direction=ES](url). and for creating same display like in that online page,  i expect like follow.

वृक्ष 	                vRkSa 	                m.    tree
गुल्म 	                gulma 	                m. 	 cluster  [ of trees ]
वृक्षक 	        vRkSaka 	                m. 	 small tree
आम्र 	                Amra 	                m. 	mango tree
वटवृक्ष 	        vaTavRkSa 	        m. 	banyan tree  [ Ficus benghalensis -  Bot. ]
विभागपरम्परा 	vibhAgaparamparA  f. 	directory tree  [ computer ]

this type of table i expected.
and it is giving like 
वृक्ष 	vRkSa 	m. 	tree 	
गुल्म 	gulma 	m. 	cluster  [ of trees ] 	
वृक्षक 	vRkSaka 	m. 	small tree 	
आम्र 	Amra 	m. 	mango tree 	
वटवृक्ष 	vaTavRkSa 	m. 	banyan tree  [ Ficus benghalensis -  Bot. ] 	
विभागपरम्परा 	vibhAgaparamparA 	f. 	directory tree  [ computer ]

**Comment by vvasuki** [comment]
I'd suggest keeping it simple, and follow the usual babylon file pattern.

So, you start with `│वृक्ष│vRkSa│m.│tree` to get:
वृक्ष
वृक्ष vRkSa m.<br>tree

**Comment by damooo** [comment]
will try to push it with in tomorrow morning, i.e with in five hours. along with zim  file

**Comment by vvasuki** [comment]
Cool! Please remember to close the github issues you've fixed (I'll reopen
if there's any problem). That way we can track what projects we can
announce to users.

2016-05-04 14:36 GMT-07:00 श्रीराम <notifications@github.com>:

> will try to push it with in tomorrow morning, i.e with in five hours.
> along with zim file
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sanskrit-coders/stardict-sanskrit/issues/8#issuecomment-217011162>
>



-- 
--
Vishvas /विश्वासः

**Comment by damooo** [comment]
Sorry for late,, But one surprising result here : )
Update
--------------------

This is babylon, bgl, stardict files of spokensanskrit.de

with .bgl dictionary, we can have colors, and  formatting. And golden dict
officially supports bgl files on both desktop and mobile.

AS WE ARE USING .BABYLON EXTENSION FILES TO CREATE STARDICT FILES,
.GLS IS FOR CREATING BABYLON .BGL FILES

.gls and .babylon  files are same, but .gls contains  tags for formatting.
So if you want to remove those tags run rmtags.sh , and then  it is 
stardict compiler compatable  babylon file.

as spokensanskrit neatly orders with priority, and even gives results
if the search word is a part of any sentence, or word. and that too with
correct priorities, and much advanced algorithm. So  golden dict
search feature, we cannot actually customise, or give priorities
or tabulate relevent results and etymologically related results too.
 so for that reason, first created search result from 
spokensanskrit,, and created content thus,,  and amolgamated with goldendict search terms.

So now we can get completely same essense of spokensanskrit, and dispay too.
along with  multi word  results from goldendict. Use double click feature, as it
is too convinient in this case.

And it can ussed as nice brigdge between all dictionaries, as it lists all possible
same meaning words  without description at one  place, and again it is both sa-En and En-sa
search also supported. 

And if you have babylon10 installed in your windows, as bgl is avialable, you can use
it to fully utilise babylon translation algorithms, and even it's integration with MS office.
And instant popups everywhere, and all from it. But their software is propriarity.

Some random search words to give an idea :

desired
red
rudhira
having
mRtajAta
trunk

**Comment by damooo** [comment]
Sorry for late,, But one surprising result here : )
Update
--------------------

This is babylon, bgl, stardict files of spokensanskrit.de

with .bgl dictionary, we can have colors, and  formatting. And golden dict
officially supports bgl files on both desktop and mobile.

AS WE ARE USING .BABYLON EXTENSION FILES TO CREATE STARDICT FILES,
.GLS IS FOR CREATING BABYLON .BGL FILES

.gls and .babylon  files are same, but .gls contains  tags for formatting.
So if you want to remove those tags run rmtags.sh , and then  it is 
stardict compiler compatable  babylon file.

as spokensanskrit neatly orders with priority, and even gives results
if the search word is a part of any sentence, or word. and that too with
correct priorities, and much advanced algorithm. So  golden dict
search feature, we cannot actually customise, or give priorities
or tabulate relevent results and etymologically related results too.
 so for that reason, first created search result from 
spokensanskrit,, and created content thus,,  and amolgamated with goldendict search terms.

So now we can get completely same essense of spokensanskrit, and dispay too.
along with  multi word  results from goldendict. Use double click feature, as it
is too convinient in this case.

And it can ussed as nice brigdge between all dictionaries, as it lists all possible
same meaning words  without description at one  place, and again it is both sa-En and En-sa
search also supported. 

And if you have babylon10 installed in your windows, as bgl is avialable, you can use
it to fully utilise babylon translation algorithms, and even it's integration with MS office.
And instant popups everywhere, and all from it. But their software is propriarity.

Some random search words to give an idea :

desired
red
rudhira
having
mRtajAta
trunk

**Comment by vvasuki** [comment]
Very good news, thanks dAmodara!
I've moved the files into sa-head.

requests:
* सिंहपुष्पी|siMhapuSpI|f.|heart fern|siMhapuShpii -> In such headword lists, stuff like f., n., m., adj. etc.. should be removed.
* Please rename dictionaries to not include version number - example sps rather than sps3, spokensanskrit instead of spokensanskrit4.2.

**Comment by damooo** [comment]
will update now,and i forgot about version  numbers, will remove them : )

**Comment by damooo** [comment]
updated with all fixes.

**Comment by damooo** [comment]
Removed non optitrans latin-transliterated headwords .repetitions too removed. Soon will remove their html, and write it from scratch with hyperlinks.
