### ISSUE TITLE
XYZ.has_corrupt_chars.babylon

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#80]
Recently I saw in one of my dictionaries Bohtlingk-Sanskrit-Worterbuch-in-kurzerer-Fassung.has_corrupt_chars_babylon

I would request if only the line number and the corrupt character can be noted in this, it would be great.
I was not able to locate the corrupt character in this multiMB file.

**Comment by vvasuki** [comment]
Not sure how to solve this @drdhaval2785 - just ensure that every character is UTF-8. If you can use it without error to generate stardicts without error, no need to bother (atleast for now).

**Comment by drdhaval2785** [comment]
I guess so. This is much ado about nothing. 
Problem not reproducible.

**Comment by vvasuki** [comment]
If I remember correctly, problem is usually in the last line of the file - check the errors you've listed recently such as :

`** (process:3469): WARNING **: Line 27639, bad definition!!!`
