### ISSUE TITLE
Add LICENSE.xml to the tar files

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#82]
Now all Cologne dictionaries have LICENSE.xml in their directory.
Can you modify the make_tarballs.sh to include these files for shipping?
Once this is done, I can sync latest files from Cologne servers. @vvasuki

**Comment by vvasuki** [comment]
Done long time ago :-) Let me know if they're not included in the tar files.

**Comment by drdhaval2785** [comment]
They are not included.

**Comment by vvasuki** [comment]
Ah. Regex error fixed - plz sync dict-tools and retry.
