### ISSUE TITLE
Heritage_Resources on github

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-coders/stardict-sanskrit#84]
https://gitlab.inria.fr/huet/Heritage_Resources everything Huet had in XML is open now. Next and last step left is http://kjc-sv013.kjc.uni-heidelberg.de/dcs/. It took me 11 years to convince Huet that it's a bad idea to be as closed as JNU is.

**Comment by vvasuki** [comment]
Thanks for the notification! INRIA declensions and conjugations have long been distributed as stardict files (and I recently combined and improved lookup in them as well)
