### ISSUE TITLE
tars.md and tars out of sync

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/stardict-sanskrit#85]
I received 2 error reports ([rep1](https://pastebin.com/raw/rVrwRfjs)) pertaining to dicts in https://github.com/sanskrit-coders/stardict-sanskrit/tree/master/sa-head/en-entries/tars :
For example: https://github.com/sanskrit-coders/stardict-sanskrit/raw/master/sa-head/en-entries/tars/apte-sa__2017-04-02_20-23-08__6MB.tar.gz is referred to in tars.MD, but not found in stardict-sanskrit/sa-head/en-entries/tars/ . All the tar files were updated, but tars.MD was not when @drdhaval2785 checked in the last change there 5 days ago. @drdhaval2785 - any idea how this happened?

**Comment by drdhaval2785** [comment]
Multi MB (yet not fat enough to call it multi GB, but soon will be) commit may have broken.
I remember putting git push origin master on and then going off to sleep. 
I feel even in the morning, it may not have uploaded the giant commit.
I give up.
Please make it a bit developer friendly.
Currently babylon, stardict files etc are also uploaded, tars.gz are also uploaded, releases also have tars.gz uploaded.
Why these much tracking? Keep only babylon tracked. and tars.gz can be done via upload in release.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-coders/stardict-sanskrit/commit/983bc952c6bfcf15bd5c13aea7876f24009c5dd3 removed the old April versions of three dictionaries. But the latest may not have been uploaded. Let me see if reverting this commit helps.

**Comment by vvasuki** [comment]
I fixed this by running this command: 
```
make tarlist
bash ../../bin/update_tars_md.sh /home/vvasuki/stardict-sanskrit/sa-head/en-entries/tars https://github.com/sanskrit-coders/stardict-sanskrit/raw/master/sa-head/en-entries/tars
```

Wrong diagnosis, btw, @drdhaval2785 . ननु सम्यगेव सञ्चिकानाम् उपारोपणम् जातम्। नूतनम् tars.MD तु न नवीकृतं कथञ्चित्, न च तत्त्वया लक्षितम्। शक्नोष्येव release-उपयोगं कर्तुम्। तदेव श्रेयस इति सत्यम् - किञ्च तत्र भवादृशाः प्रयोक्तार एव शरण्याः। नास्ति तत्र tracking-सम्बन्धः (tar-सञ्चिकानाम् रक्षणेनाऽपि release-सञ्चिकानाम् उपयोगः शक्यः)।
