### ISSUE TITLE
Issues in dhAtu-pATha-kRShNamAchArya tsv

### ISSUE THREAD

**Issue by kmadathil** [sanskrit-coders/stardict-sanskrit#87]
ref: kmadathil/sanskrit_parser#41

सदोषा दृश्यन्ते काश्चन राजयः

Line 1064-1066 - पू धातुः  
Line 1245 - मस्ज् धातुः

**Comment by vvasuki** [comment]
सूचनयोपकृतोऽहम् अङ्ग। अपि शोधयेस् ताः‌ पङ्क्तीः? अधिकृतोऽसि सद्य एव।

**Comment by vvasuki** [comment]
(अन्तर्जाल एव सञ्चिका-शोधनं शक्यम्, repository-अवारोपणस्यापेक्षा नास्ति)

**Comment by kmadathil** [comment]
धन्यवादः | सञ्चिका यथाशक्यं शोधिता मया | दृष्ट्वा इदं पिधेहि |
