### ISSUE TITLE
sanskrit english machine translation database development

### ISSUE THREAD

**Issue by damooo** [sanskrit-coders/stardict-sanskrit#9]
This issue tracks progress and issues in preparing an open source sanskrit to english machine translation database, with parallal translations for every word.with out description and details.. just one snippet translation word, so that we can create algorithm in future to analyse a sentence and grammar,, sandhis, and take data from this database, and can form translation sentences.

**Comment by damooo** [comment]
data retrieved from spokensanskrit added to sanskrit.table file., and added readme with procedure and plans

**Comment by gasyoun** [comment]
> data retrieved from spokensanskrit

Why not from Cologne directly, @damooo ?
