### ISSUE TITLE
DICTZIP error: Read file error

### ISSUE THREAD

**Issue by asheeshkumar96** [sanskrit-coders/stardict-sanskrit#95]
I am using GoldenDict in Ubuntu 18.04. I installed from official repositories along with which came along with WordNet 3.0 (En-En). I downloaded your dictionaries in my android which are working fine in EBdict. I copied dictdata folder to my laptop, added dictionaries to GoldenDict but when I search any entry then I got "DICTZIP error: Read file error". 
Below are two screenshots in which WordNet is proccessed while kalpadrum in not processed . 

![image](https://user-images.githubusercontent.com/33876206/47897266-0c255000-de97-11e8-9284-53c4945076ba.png)
![image](https://user-images.githubusercontent.com/33876206/47897280-16dfe500-de97-11e8-8711-cec80d5d1ada.png)

**Comment by vvasuki** [comment]
Can you download kalpadruma-sa files from this repo and retry? Or consider using one of the options described in https://sanskrit-coders.github.io/site/pages/dictionaries/offline.html#how-to-install-and-use-dictionaries-on-your-device , rather than copying over the dictdata folder.

Please reopen if this doesn't work.

**Comment by asheeshkumar96** [comment]
Take a look at this screen. Let me know whether everything is fine. 

![downloader py output](https://user-images.githubusercontent.com/33876206/47954351-7af5cc80-dfaf-11e8-9e6c-1e2a7ab38daf.png)

**Comment by asheeshkumar96** [comment]
Finally dict-tools.jar has worked with the command 
 java -jar dict-tools.jar install /home/asheesh/Downloads/sanskrit-dict/ https://raw.githubusercontent.com/sanskrit-coders/stardict-dictionary-updater/master/dictionaryIndices.md 

![dict-tools output](https://user-images.githubusercontent.com/33876206/47954553-4256f280-dfb1-11e8-92b5-d137d35e4c62.png)

**Comment by asheeshkumar96** [comment]
Now, It is working perfect. Thanks. 
![screenshot from 2018-11-03 22-04-57](https://user-images.githubusercontent.com/33876206/47954795-b21aac80-dfb4-11e8-86b5-8f8d2c9eaa4b.png)

**Comment by vvasuki** [comment]
yes - the python installer is not being maintained, while the java installer works fine.
